## Title: specimen from organism "derived from" relationships

#### Description

Checks that 'source' of 'derived from' relationship has a material
'specimen from organism' and 'target' has a material 'organism'

#### Query
[source,cypher]
----
MATCH (a:Biosample)-[r:DERIVED_FROM]->(b:Biosample) WHERE a.material='specimen from organism' AND NOT b.material='organism' RETURN a.accession, b.accession
----

## Title: pool of specimens "derived from" relationships

#### Description

Checks that 'source' of 'derived from' relationship has a material
'pool of specimens' and 'target' has a material 'specimen from organism'

#### Query
[source,cypher]
----
MATCH (a:Biosample)-[r:DERIVED_FROM]->(b:Biosample) WHERE a.material='pool of specimens' AND NOT b.material='specimen from organism' RETURN a.accession, b.accession
----

## Title: purified cells "derived from" relationships

#### Description

Checks that 'source' of 'derived from' relationship has a material
'cell specimen' and 'target' has a material 'specimen from organism'

#### Query
[source,cypher]
----
MATCH (a:Biosample)-[r:DERIVED_FROM]->(b:Biosample) WHERE a.material='cell specimen' AND NOT b.material='specimen from organism' RETURN a.accession, b.accession
----

## Title: cell culture "derived from" relationships

#### Description

Checks that 'source' of 'derived from' relationship has a material
'cell culture' and 'target' has a material 'specimen from organism' or
'target' has a material 'cell specimen'

#### Query
[source,cypher]
----
MATCH (a:Biosample)-[r:DERIVED_FROM]->(b:Biosample) WHERE a.material='cell culture' AND NOT (b.material='specimen from organism' OR b.material='cell specimen') RETURN a.accession, b.accession
----