# Get location of human settlement
# @endpoint http://query.wikidata.org/sparql

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?settlement ?name ?coordinate
WHERE {
    ?settlement wdt:P31/wdt:P279* wd:Q486972 ; # instance of subclasses of human settlement
                wdt:P625 ?location ;           # coordinate location
                rdfs:label ?label .
    FILTER(lang(?label) = "en")
    BIND(str(?label) AS ?name)
    BIND(str(?location) AS ?coordinate)
}
