#!/bin/bash

FULLPATH="$(dirname $(readlink -f $0))"

source ${CONDA_PREFIX=${3-~/berryconda3}}/bin/activate
source ~/.poetry/env

cd ${FULLPATH}
envsubst '$PWD' < asterix.lighttpd.conf.template > asterix.lighttpd.conf
exec uvicorn --host 0.0.0.0 --port 8000 web_server.main:app
